services:
  - type: web
    name: note-web-downloader
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn --config gunicorn.conf.py src.main:app"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
